services:
    fos_user.doctrine_registry:
        alias: doctrine

    fos_user.registration.controller:
        class: AppBundle\Controller\RegistrationController
        arguments: ['@event_dispatcher', '@fos_user.registration.form.factory', '@fos_user.user_manager']

    appbundle.password_resetting:
        class: FOS\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
