# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    fos_user.doctrine_registry:
        alias: doctrine

    fos_user.registration.controller:
        class: AppBundle\Controller\RegistrationController
        arguments: ['@service_container']

    appbundle.password_resetting:
        class: FOS\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    # appbundle.form.registration:
    #     class: AppBundle\Form\Type\RegistrationFormType
    #     tags:
    #         - { name: form.type, alias: app_user_registration }
