services:
    fos_user.doctrine_registry:
        alias: doctrine

    fos_user.registration.controller:
        class: AppBundle\Controller\RegistrationController
        arguments: ['@service_container']

    appbundle.password_resetting:
        class: FOS\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
