app:
    resource: "@AppBundle/Controller/"
    type:     annotation

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"